export { configureGit } from './configure-git.mjs'
export { configureNetlify } from './configure-netlify.mjs'
export { copyTemplates } from './copy-templates.mjs'
export { createProjectDir } from './create-project-dir.mjs'
export { generateReadme } from './generate-readme.mjs'
export { getProjectInfo } from './get-project-info.mjs'
export { installDependencies } from './install-dependencies.mjs'
export { replacePlaceholders } from './replace-placeholders.mjs'
