const lintDependencies = [
  '@eslint/compat',
  '@types/eslint',
  'eslint-config-prettier',
  'eslint-plugin-import',
  'eslint-plugin-svelte',
  'eslint',
  'globals',
  'prettier',
  'stylelint-config-recess-order',
  'stylelint-config-standard-scss',
  'stylelint-order',
  'stylelint',
  'typescript-eslint',
  'typescript',
]

export default {
  _shared: {
    devDependencies: [...lintDependencies, 'groq'],
  },
  'svelte-kit': {
    githubSrc: 'sveltejs/kit/packages/create-svelte/templates/skeleton',
    remove: ['.ignore', '.meta.json', 'package.template.json', 'static/favicon.png'],
    replace: ['.env', 'package.json', 'svelte.config.js', 'src/config.js'],
    dependencies: [],
    devDependencies: [
      ...lintDependencies,
      '@fortawesome/fontawesome-free',
      '@james-camilleri/sanity-web-image',
      '@james-camilleri/type-scale',
      '@poppanator/sveltekit-svg',
      '@portabletext/svelte',
      '@portabletext/types',
      '@rollup/plugin-replace',
      '@sveltejs/kit',
      '@sveltejs/vite-plugin-svelte',
      // TODO: Remove this when view transitions are added to the global TS browser types.
      '@types/dom-view-transitions',
      'eslint-plugin-svelte',
      'lorem-ipsum',
      'postcss-html',
      'prettier-plugin-svelte',
      'sanitize.css',
      'sass',
      'stylelint-config-html',
      'svelte-check',
      'svelte-inline-svg',
      'svelte-loading-spinners',
      'svelte',
      'sveltekit-superforms',
      'zod',
      'tslib',
      'vite',
    ],
  },
  sanity: {
    replace: [
      '.env',
      'package.json',
      'netlify/functions/optimise-image.ts',
      'netlify/functions/update-image-metadata.ts',
      'scripts/clean-assets.js',
      'scripts/generate-breakpoints.js',
    ],
    dependencies: [
      '@james-camilleri/replace-sanity-favicon',
      '@james-camilleri/sanity-web-image',
      '@james-camilleri/logger',
      '@sanity/client',
      '@sanity/vision',
      'react-dom',
      'react-icons',
      'react-is',
      'react',
      'sanity',
      'styled-components',
    ],
    devDependencies: [...lintDependencies, '@netlify/functions', '@sanity/eslint-config-studio'],
  },
}
