export default {
  'svelte-kit': {
    githubSrc: 'sveltejs/kit/packages/create-svelte/templates/skeleton',
    remove: [
      '.ignore',
      '.meta.json',
      'package.template.json',
      'static/favicon.png',
    ],
    replace: ['.env', 'package.json', 'src/config.js'],
    dependencies: ['@sanity/client', 'nodemailer'],
    devDependencies: [
      '@fortawesome/fontawesome-free',
      '@james-camilleri/sanity-web-image',
      '@poppanator/sveltekit-svg',
      '@portabletext/svelte',
      '@portabletext/types',
      '@rollup/plugin-replace',
      '@sanity/image-url', // TODO: Make this dependent on cms option.
      '@sveltejs/adapter-auto',
      '@sveltejs/kit',
      '@typescript-eslint/eslint-plugin',
      '@typescript-eslint/parser',
      'env-cmd',
      'eslint-config-prettier',
      'eslint-plugin-svelte3',
      'eslint',
      'lorem-ipsum',
      'postcss-html',
      'prettier-plugin-svelte',
      'prettier',
      'sanitize.css',
      'sass',
      'stylelint-config-html',
      'stylelint-config-prettier-scss',
      'stylelint-config-recess-order',
      'stylelint-config-sass-guidelines',
      'stylelint-config-standard-scss',
      'stylelint-order',
      'stylelint',
      'svelte-check',
      'svelte-inline-svg',
      'svelte-loading-spinners',
      'svelte-preprocess',
      'svelte',
      'tslib',
      'typescript',
      'vite',
    ],
  },
  sanity: {
    replace: [
      '.env',
      'package.json',
      'netlify/functions/optimise-image.ts',
      'netlify/functions/update-image-metadata.ts',
      'scripts/clean-assets.js',
      'scripts/generate-breakpoints.js',
    ],
    dependencies: [
      '@james-camilleri/replace-sanity-favicon',
      '@james-camilleri/sanity-web-image',
      '@james-camilleri/logger',
      '@sanity/client',
      '@sanity/vision',
      'react-dom',
      'react-icons',
      'react-is',
      'react',
      'sanity',
      'styled-components',
      'url', // TODO: Remove when Sanity fixes their bug.
    ],
    devDependencies: [
      '@netlify/functions',
      '@sanity/eslint-config-studio',
      'env-cmd',
      'eslint',
      'prettier',
      'typescript',
    ],
  },
}
